Replace custom webpack integration with webpacker
porkchopclub/porkchop pull request #106
Opened 2017-02-24 08:32 UTC by jhawthorn

What does it do?
----------------
Adds webpacker and moves javascripts under webpacker

How does it work?
-----------------
Moves the javascripts from `app/webpack` into `app/javascript`, the new canonical location for webpack.

Webpacker will compile a "pack" for each file in the `app/javascript/packs` directory and places them in `public/packs/` without going through sprockets. Those packs can then be linked to using `javascript_pack_tag` (there's a `public/packs/digests.json` which powers this).

The new commands for invoking webpack are:
`bin/webpack`
`bin/webpack-watcher`
`bin/webpack-dev-server` (which has some related configuration in config/environments/development.rb)

Anything to consider when deploying?
------------------------------------
Yeah, it might not work, but I think it will. The `yarn run compile` commands now just call `bin/webpack`

Screenshots (Optional)
----------------------
![](https://pbs.twimg.com/media/C5ZTX9MWYAA9n0N.jpg:large)

2017-02-24 17:34 UTC, jarednorman requested changes
This looks all fine except I'm wary of the Babel config change.

2017-02-24 17:34 UTC, jarednorman commented on config/webpack/shared.js
> +            [ 'latest', { 'es2015': { 'modules': false } } ]
Doesn't look like you've removed the `.babelrc` which specifies different options than this. Probably need to axe it and move that stuff here? Or if this config respects the `.babelrc`, move those options there? Or explain what's goin' on here so I feel better.

2017-02-25 01:36 UTC, jhawthorn commented on config/webpack/shared.js
> +            [ 'latest', { 'es2015': { 'modules': false } } ]
I have moved the options in here.

2017-02-25 06:36 UTC, jarednorman approved these changes
Go for it.

2017-02-26 07:02 UTC, jhawthorn commented
Going for it

2017-02-26 07:02 UTC, merged

2017-02-26 07:08 UTC, jhawthorn commented
Gone

2017-02-26 07:08 UTC, jhawthorn commented
Update: [went](https://travis-ci.org/PorkChopClub/porkchop/builds/205449399)